### ISSUE TITLE
Non-uniform ellipse scaling crashes

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#140]
Some ellipses appear to scale correctly when part of a block, but occasionally the presence of an ellipse in a block which is being scaled non-uniformly causes `Insert.virtual_entities()` to crash

For example:
```python
import sys
from typing import cast

import ezdxf
from ezdxf.entities import Insert


def main():
    doc = ezdxf.readfile(sys.argv[1])
    print(ezdxf.version)
    model_space = doc.modelspace()
    for entity in model_space:
        print(entity.dxftype())
        if entity.dxftype() == 'INSERT':
            entity = cast(Insert, entity)
            d = entity.dxf
            block_name = d.name
            print(f'Insert entity at {entity.dxf.insert} with scaling {entity.has_scaling} ({entity.has_uniform_scaling})')
            print(f'scaling = {d.xscale}, {d.yscale}, {d.zscale}')
            print(f'block = {block_name}')

            print('\nentities from block:')
            block = doc.blocks[block_name]
            for child in block:
                print(f'child: {child.dxftype()}')
                for key, value in child.dxf.all_existing_dxf_attribs().items():
                    print(f' - {key}: {value}')

            print('\nvirtual entities:')
            entities = entity.virtual_entities(non_uniform_scaling=True)
            for child in entities:
                print(f'child: {child.dxftype()}')


if __name__ == '__main__':
    main()

```
I added a print statement in `rytz_axis_construction()` where the crash occurs to print the arguments it was passed.

crash_test_1.dxf
![crash_test_1](https://user-images.githubusercontent.com/4923501/79968807-8c26e780-8488-11ea-998c-21809ec14963.png)
crash_test_2.dxf
![crash_test_2](https://user-images.githubusercontent.com/4923501/79968810-8cbf7e00-8488-11ea-919b-d8e5a8d6a238.png)
[bug_report.zip](https://github.com/mozman/ezdxf/files/4515368/bug_report.zip)

The output from running the script on `crash_test_2.dxf`:
```
(0, 12, 0, 'release')
INSERT
Insert entity at (234.2560357296471, 151.7235633885176, 0.0) with scaling True (False)
scaling = 1, 0.2, 1
block = BLOCK_1

entities from block:
child: ELLIPSE
 - handle: 28E
 - owner: 23A
 - layer: 0
 - center: (-0.3458830587136248, -25.87866703008919, 0.0)
 - major_axis: (-1.42e-14, -95.6311028028473, 0.0)
 - extrusion: (0.0, 0.0, 1.0)
 - ratio: 0.7571630573128669
 - start_param: 0.0
 - end_param: 6.283185307179584

virtual entities:
in rytz_axis_construction((10.54993213272502, -15.953408567652433, 0.0), (60.39665802822498, 39.9400943402867, 0.0))
Traceback (most recent call last):
  File "/home/matthew/bug_report.py", line 36, in <module>
    main()
  File "/home/matthew/bug_report.py", line 31, in main
    for child in entities:
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/explode.py", line 260, in virtual_block_reference_entities
    major_axis, _, ratio = rytz_axis_construction(major_axis, minor_axis)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/math/construct2d.py", line 415, in rytz_axis_construction
    raise ArithmeticError('Conjugated axis required, invalid source data.')
ArithmeticError: Conjugated axis required, invalid source data.
```

**Comment by mozman** [comment]
I am still not sure if the axis construction works for every case, but I don't know a better solution.
