### ISSUE TITLE
virtual_entities crash

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#149]
I have encountered a situation where calling `insert.virtual_entities()` on an Insert of a block with a certain Hatch entity crashes.

The cause of this crash is that `ezdxf.entities.hatch.LineEdge.transform_to_wcs()` calls `ezdxf.entities.hatch._transform_2d_ocs_vertices()` which expects vertices to have type `List[Tuple[float, float]]`, however the start and end points of the LineEdge have been set as `Vector` so vertices has type `List[Vector]` which means the unpacking with `for x, y in vertices` doesn't unpack as expected.
```
Traceback (most recent call last):
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/explode.py", line 244, in virtual_block_reference_entities
    entity.transform_to_wcs(brcs)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 500, in transform_to_wcs
    self.paths.transform_to_wcs(ucs, elevation=elevation, extrusion=extrusion)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 592, in transform_to_wcs
    path.transform_to_wcs(ucs, elevation=elevation, extrusion=extrusion)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 809, in transform_to_wcs
    edge.transform_to_wcs(ucs, elevation=elevation, extrusion=extrusion)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 1001, in transform_to_wcs
    self.start, self.end = _transform_2d_ocs_vertices(ucs, (self.start, self.end), elevation, extrusion)
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 966, in _transform_2d_ocs_vertices
    ocs_vertices = [Vector(x, y, elevation) for x, y in vertices]
  File "/home/matthew/anaconda3/envs/physical_map_processing/lib/python3.8/site-packages/ezdxf/entities/hatch.py", line 966, in <listcomp>
    ocs_vertices = [Vector(x, y, elevation) for x, y in vertices]
ValueError: too many values to unpack (expected 2)
```
(I replaced `ocs_vertices` with a list rather than a generator so the traceback is easier to follow)

I did some investigating and found that the `LineEdge` start and end are being assigned `Vector` objects from `ezdxf.entities.hatch.LineEdge.load_tags`

Should the types for `LineEdge.start` and `LineEdge.end` be `Vector` instead? or should `load_tags()` not be converting them to `Vector` in the first place?

**Comment by mozman** [comment]
Yes, `Vec2()` is required, also for other edge type coordinates
