### ISSUE TITLE
Exception in virtual entities

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#180]
in commit 2fa8159e8755a9a7171bb995bbdc788a36963224 the try/catch around `entity.virtual_entities()` was removed. This was added initially because If there is a bug in ezdxf it is usually preferable to continue drawing even if an individual entity cannot be drawn. Perhaps an interface should be added to let the front end decide what to do when it cannot draw a particular entity.

Related to this. I have written a script to use a dummy drawing backend to draw every layout of every CAD file I have access to in order to find bugs. 
```
Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 54, in _draw_dxf_file
    Frontend(ctx, out).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 71, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 115, in draw_entity
    self.draw_composite_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 320, in draw_composite_entity
    self.draw_entities(set_opaque(entity))
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 77, in draw_entities
    for entity in entities:
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 300, in set_opaque
    for child in entity.virtual_entities():
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/explode.py", line 438, in virtual_leader_entities
    raise ValueError('More than 2 vertices required.')
ValueError: More than 2 vertices required.
```

I can't give you the complete file but I can give you the information about that particular LEADER
```
>>> leader.dxf.all_existing_dxf_attribs()
{'handle': '9F1F', 'owner': '1F', 'layer': '--', 'color': 3, 'dimstyle': 'SAH 1-250'}
>>> leader.xdata.data
OrderedDict([('ACAD', [DXFTag(1001, 'ACAD'), DXFTag(1000, 'DSTYLE'), DXFTag(1002, '{'), DXFTag(1070, 147), DXFTag(1040, 1.0), DXFTag(1070, 77), DXFTag(1070, 0), DXFTag(1002, '}')])])
>>> leader.vertices
[(-3904636.944095615, -5545354.454804033, 0.0), (-3905658.372267556, -5546501.036443039, 0.0)]
```

I tried writing a script to extract just this entity, but the crash doesn't occur when drawing the dxf file with the isolated element so I'm not sure what I'm doing wrong.
```
import argparse
import ezdxf

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('cad_file')
    parser.add_argument('--out', required=True)
    parser.add_argument('--keep', nargs='*')
    args = parser.parse_args()

    doc = ezdxf.readfile(args.cad_file)
    doc_out = ezdxf.new()
    out_modelspace = doc.modelspace()
    for entity_id in args.keep:
        results = list(doc.query(f'*[handle=="{entity_id}"]i'))
        assert len(results) == 1
        out_modelspace.add_entity(results[0])
    doc_out.saveas(args.out)


if __name__ == '__main__':
    main()

```

**Comment by mozman** [comment]
I see your good intentions, but bugs have to fixed, they don't go away by hiding it.

This error in virtual_leader_entities() is already fixed.
