### ISSUE TITLE
Exception in virtual entities

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#182]
```
Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/polyline.py", line 854, in __getitem__
    return self.vertices[pos].dxf.location
KeyError: (1, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/find_ezdxf_crashes.py", line 55, in _draw_dxf_file
    Frontend(ctx, out).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 71, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 115, in draw_entity
    self.draw_composite_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 311, in draw_composite_entity
    self.draw_entities(entity.virtual_entities())
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 113, in draw_entity
    self.draw_polyline_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 267, in draw_polyline_entity
    MeshBuilder.from_polyface(e),
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/render/mesh.py", line 227, in from_polyface
    vertices[n + 1, m + 1],
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/polyline.py", line 856, in __getitem__
    raise const.DXFIndexError(repr(pos))
ezdxf.lldxf.const.DXFIndexError: (1, 3)
Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/polyline.py", line 854, in __getitem__
    return self.vertices[pos].dxf.location
KeyError: (1, 3)
```

the top level entity is an INSERT entity, the next level is a POLYLINE entity
```
>>> for k, v in self.vertices.items():
...     print(f'{k}: {v.dxf.location}')
...     
(0, 0): (16606.65151901649, 81.88147523282441, 2099.9999999999995)
(0, 1): (16606.65151901649, 81.88147523282441, 1199.9999999999998)
(0, 2): (16606.65151901649, 81.88147523282441, 1199.9999999999998)
(1, 0): (16606.65151901649, 1281.8814752328244, 2099.9999999999995)
(1, 1): (16606.65151901649, 1281.8814752328244, 1199.9999999999998)
(1, 2): (16606.65151901649, 1281.8814752328244, 1199.9999999999998)
(2, 0): (16626.65151901649, 1281.8814752328244, 2099.9999999999995)
(2, 1): (16626.65151901649, 1281.8814752328244, 1199.9999999999998)
(2, 2): (16606.65151901649, 1281.8814752328244, 1199.9999999999998)
(3, 0): (16626.65151901649, 81.88147523282441, 2099.9999999999995)
(3, 1): (16626.65151901649, 81.88147523282441, 1199.9999999999998)
(3, 2): (16606.65151901649, 81.88147523282441, 1199.9999999999998)
(4, 0): (16626.65151901649, 81.88147523282441, 2099.9999999999995)
(4, 1): (16626.65151901649, 81.88147523282441, 2099.9999999999995)
(4, 2): (16606.65151901649, 81.88147523282441, 2099.9999999999995)
(5, 0): (16626.65151901649, 1281.8814752328244, 2099.9999999999995)
(5, 1): (16626.65151901649, 1281.8814752328244, 2099.9999999999995)
(5, 2): (16606.65151901649, 1281.8814752328244, 2099.9999999999995)
```

I can share the problematic dxf if the sensitive information can be scrubbed from it

**Comment by mbway** [comment]
on different CAD files, there is a similar crash, probably the same cause
```
Traceback (most recent call last):
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/polyline.py", line 854, in __getitem__
    return self.vertices[pos].dxf.location
KeyError: (2, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 54, in _draw_dxf_file
    Frontend(ctx, out).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 71, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 115, in draw_entity
    self.draw_composite_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 311, in draw_composite_entity
    self.draw_entities(entity.virtual_entities())
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 113, in draw_entity
    self.draw_polyline_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 267, in draw_polyline_entity
    MeshBuilder.from_polyface(e),
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/render/mesh.py", line 226, in from_polyface
    vertices[n + 1, m],
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/polyline.py", line 856, in __getitem__
    raise const.DXFIndexError(repr(pos))
ezdxf.lldxf.const.DXFIndexError: (2, 0)

```

**Comment by mozman** [comment]
There is an [dxf2code](https://ezdxf.mozman.at/docs/addons/dxf2code.html) add-on, which let you write single DXF entities as python code, this script writes all LEADER entities into `leaders.py`:

```python

doc = ezdxf.readfile(r"D:\Source\dxftest\GDAL\leader-mleader.dxf")
msp = doc.modelspace()

source = entities_to_code(msp.query('LEADER'))
with open('leaders.py', mode='wt') as f:
    f.write(source.code_str())
```

**Comment by mbway** [comment]
this entity causes the (2, 0) version of the crash:
```python
e = layout.new_entity(
    'POLYLINE',
    dxfattribs={
        'layer': "0",
        'color': 0,
        'lineweight': -1,
        'elevation': (0.0, 0.0, 0.0),
        'flags': 48,
        'm_count': 2,
        'n_count': 6,
    },
)
e.append_vertex((25041.94191089287, 29272.95055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25020.29127589287, 29285.45055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25020.29127589287, 29310.45055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25041.94191089287, 29322.95055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25063.59254589287, 29310.45055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25063.59254589287, 29285.45055566061, 0.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25041.94191089287, 29272.95055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25020.29127589287, 29285.45055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25020.29127589287, 29310.45055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25041.94191089287, 29322.95055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25063.59254589287, 29310.45055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
e.append_vertex((25063.59254589287, 29285.45055566061, 50.0), dxfattribs={'color': 0, 'lineweight': -1, 'flags': 64})
```

This entity causes the (1, 3) version of the crash
```python
e = layout.new_entity(
    'POLYLINE',
    dxfattribs={
        'layer': "GROUP1$0",
        'lineweight': -1,
        'elevation': (0.0, 0.0, 0.0),
        'flags': 16,
        'm_count': 6,
        'n_count': 3,
    },
)
e.append_vertex((16606.65151901649, 81.88147523282441, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 81.88147523282441, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 81.88147523282441, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 1281.8814752328244, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 1281.8814752328244, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 1281.8814752328244, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 1281.8814752328244, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 1281.8814752328244, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 1281.8814752328244, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 81.88147523282441, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 81.88147523282441, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 81.88147523282441, 1199.9999999999998), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 81.88147523282441, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 81.88147523282441, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 81.88147523282441, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 1281.8814752328244, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16626.65151901649, 1281.8814752328244, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
e.append_vertex((16606.65151901649, 1281.8814752328244, 2099.9999999999995), dxfattribs={'lineweight': -1, 'flags': 64})
```
