### ISSUE TITLE
Exception drawing circle with 0 radius

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#184]
```
EXCEPTION: ValueError(Invalid major axis (null vector).)
Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 54, in _draw_dxf_file
    Frontend(ctx, out).draw_layout(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 71, in draw_layout
    self.draw_entities(layout)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 88, in draw_entities
    self.draw_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 101, in draw_entity
    self.draw_elliptic_arc_entity(entity)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/addons/drawing/frontend.py", line 162, in draw_elliptic_arc_entity
    path = Path.from_circle(cast('Circle', entity))
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/render/path.py", line 203, in from_circle
    extrusion=circle.dxf.extrusion,
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/ellipse.py", line 73, in from_arc
    return cls(center, major_axis, extrusion, ratio, start_param, end_param, bool(ccw))
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/math/ellipse.py", line 39, in __init__
    raise ValueError(f'Invalid major axis (null vector).')
ValueError: Invalid major axis (null vector).
```

This problem arises from a CIRCLE entity having a radius of 0.0. I'm not sure whether autoCAD would draw this as a point or ignore it entirely.

**Comment by mozman** [comment]
Added some guards to `draw_elliptic_arc()` and skipping these entities.
