### ISSUE TITLE
Exception during audit

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#189]
```
EXCEPTION: AttributeError('DXFGroup' object has no attribute 'restore_integrity')
Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 53, in _draw_dxf_file
    auditor = doc.audit()
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/drawing.py", line 839, in audit
    auditor.run()
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/audit/auditor.py", line 142, in run
    self.doc.groups.audit(self)
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/entities/dxfgroups.py", line 276, in audit
    group.restore_integrity()
AttributeError: 'DXFGroup' object has no attribute 'restore_integrity'
```

**Comment by mbway** [comment]
another different exception during auditing
```
EXCEPTION: RuntimeError(dictionary changed size during iteration)
Traceback (most recent call last):
  File "find_ezdxf_crashes.py", line 53, in _draw_dxf_file
    auditor = doc.audit()
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/drawing.py", line 839, in audit
    auditor.run()
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/audit/auditor.py", line 141, in run
    self.check_database_entities()
  File "/home/matthew/src/ezdxf_upstream/src/ezdxf/audit/auditor.py", line 172, in check_database_entities
    for entity in self.doc.entitydb.values():
RuntimeError: dictionary changed size during iteration
```
