### ISSUE TITLE
exception drawing the text.dxf example

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#207]
When opening the text.dxf example from the examples folder I get this exception:

```
Traceback (most recent call last):
  File "examples/addons/drawing/cad_viewer.py", line 200, in _select_doc
    doc = ezdxf.readfile(path)
  File "ezdxf/filemanagement.py", line 137, in readfile
    doc = read(fp, legacy_mode=legacy_mode, filter_stack=filter_stack)
  File "ezdxf/filemanagement.py", line 85, in read
    return Drawing.read(stream, legacy_mode=legacy_mode, filter_stack=filter_stack)
  File "ezdxf/drawing.py", line 234, in read
    return cls.load(tag_loader, legacy_mode=legacy_mode, filter_stack=filter_stack)
  File "ezdxf/drawing.py", line 279, in load
    doc._load(tag_loader)
  File "ezdxf/drawing.py", line 326, in _load
    fill_database(sections, self.dxffactory)
  File "ezdxf/lldxf/loader.py", line 135, in fill_database
    for index, entity in enumerate(load_dxf_entities(section, factory)):
  File "ezdxf/lldxf/loader.py", line 126, in load_dxf_entities
    yield factory.load(entity)
  File "ezdxf/entities/factory.py", line 73, in load
    entity = self.entity_from_tags(tags)
  File "ezdxf/entities/factory.py", line 83, in entity_from_tags
    entity = class_.load(tags, self.doc)
  File "ezdxf/entities/dxfentity.py", line 558, in load
    entity.load_tags(tags)
  File "ezdxf/entities/dxfentity.py", line 658, in load_tags
    self.dxf = self.load_dxf_attribs(processor)
  File "ezdxf/entities/mtext.py", line 216, in load_dxf_attribs
    tags = processor.load_dxfattribs_into_namespace(dxf, acdb_mtext)
  File "ezdxf/entities/dxfentity.py", line 422, in load_dxfattribs_into_namespace
    return self.load_tags_into_namespace(dxf, tags[1:], subclass_definition)
  File "ezdxf/entities/dxfentity.py", line 470, in load_tags_into_namespace
    dxf.set(attrib.name, value)
  File "ezdxf/entities/dxfentity.py", line 231, in set
    self.__setattr__(key, value)
  File "ezdxf/entities/dxfentity.py", line 175, in __setattr__
    self.__dict__[key] = check(value)
  File "ezdxf/entities/dxfentity.py", line 164, in check
    raise DXFValueError(
ezdxf.lldxf.const.DXFValueError: Invalid value 17 for attribute "bg_fill" in entity MTEXT(#None).

```
the text.dxf file was created in AutoCAD and not modified by anything else so I assume that 17 is a valid code because I don't think AutoCAD would create an invalid dxf file

**Comment by mozman** [comment]
It depends: If you consider an undocumented value as invalid, than: YES, AutoCAD writes invalid DXF files ;-).

![image](https://user-images.githubusercontent.com/4230966/89284099-87a8c800-d64e-11ea-9a02-dd7d68fefe72.png)

No hint for a value > 2 in the DXF reference.

**Comment by mbway** [comment]
shouldn't this be caught in the audit rather than crashing the viewer?
