### ISSUE TITLE
Crash loading dxf file (invalid start_tangent)

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#252]
I'm experimenting with libredwg and have installed it into a docker container. I downloaded the `Visualization - Conference Room` dwg from [here](https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)

Then converted it to dxf with libredwg. This looks like a tricky dwg file because even ODAFileConverter doesn't seem to do a good job. The ODAFileConverter converted output looks like this:
![out](https://user-images.githubusercontent.com/4923501/96715256-367dba00-139b-11eb-9da6-98cfcf3b0075.png)
[visualization_-_conference_room.dxf.zip](https://github.com/mozman/ezdxf/files/5415588/visualization_-_conference_room.dxf.zip)

When loading the dxf file converted using libredwg it crashes:
I'm not sure whether this is because libredwg is creating an invalid dxf file or that ezdxf fails to load it
```
python examples/addons/drawing/draw_cad.py /w/output/visualization_-_conference_room.dxf --out out.png
Traceback (most recent call last):
  File "examples/addons/drawing/draw_cad.py", line 46, in _main
    doc = ezdxf.readfile(args.cad_file)
  File "ezdxf/src/ezdxf/filemanagement.py", line 153, in readfile
    doc = read(fp)
  File "ezdxf/src/ezdxf/filemanagement.py", line 93, in read
    return Drawing.read(stream)
  File "ezdxf/src/ezdxf/document.py", line 267, in read
    return cls.load(tag_loader)
  File "ezdxf/src/ezdxf/document.py", line 281, in load
    doc._load(tag_loader)
  File "ezdxf/src/ezdxf/document.py", line 297, in _load
    self._load_section_dict(sections)
  File "ezdxf/src/ezdxf/document.py", line 324, in _load_section_dict
    loader.load_and_bind_dxf_content(sections, self)
  File "ezdxf/src/ezdxf/lldxf/loader.py", line 140, in load_and_bind_dxf_content
    for index, entity in enumerate(load_dxf_entities(section)):
  File "ezdxf/src/ezdxf/lldxf/loader.py", line 132, in load_dxf_entities
    yield factory.load(ExtendedTags(entity))
  File "ezdxf/src/ezdxf/entities/factory.py", line 57, in load
    entity = cls(tags.dxftype()).load(tags)
  File "ezdxf/src/ezdxf/entities/dxfentity.py", line 175, in load
    entity.load_tags(tags, dxfversion=dxfversion)
  File "ezdxf/src/ezdxf/entities/dxfentity.py", line 198, in load_tags
    self.dxf = self.load_dxf_attribs(processor)
  File "ezdxf/src/ezdxf/entities/spline.py", line 115, in load_dxf_attribs
    processor.load_and_recover_dxfattribs(dxf, acdb_spline)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 462, in load_and_recover_dxfattribs
    tags = self.load_dxfattribs_into_namespace(dxf, subclass, index)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 385, in load_dxfattribs_into_namespace
    return self.load_tags_into_namespace(dxf, tags[1:], subclass_definition)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 432, in load_tags_into_namespace
    dxf.set(attrib.name, value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 197, in set
    self.__setattr__(key, value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 141, in __setattr__
    self.__dict__[key] = check(value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 130, in check
    raise const.DXFValueError(
ezdxf.lldxf.const.DXFValueError: Invalid value (0.0, 0.0, 0.0) for attribute "start_tangent" in entity SPLINE(#None).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/addons/drawing/draw_cad.py", line 86, in <module>
    _main()
  File "examples/addons/drawing/draw_cad.py", line 52, in _main
    doc, auditor = recover.readfile(args.cad_file)
  File "ezdxf/src/ezdxf/recover.py", line 54, in readfile
    doc, auditor = read(fp, errors=errors)
  File "ezdxf/src/ezdxf/recover.py", line 82, in read
    doc._load_section_dict(recover_tool.section_dict)
  File "ezdxf/src/ezdxf/document.py", line 324, in _load_section_dict
    loader.load_and_bind_dxf_content(sections, self)
  File "ezdxf/src/ezdxf/lldxf/loader.py", line 140, in load_and_bind_dxf_content
    for index, entity in enumerate(load_dxf_entities(section)):
  File "ezdxf/src/ezdxf/lldxf/loader.py", line 132, in load_dxf_entities
    yield factory.load(ExtendedTags(entity))
  File "ezdxf/src/ezdxf/entities/factory.py", line 57, in load
    entity = cls(tags.dxftype()).load(tags)
  File "ezdxf/src/ezdxf/entities/dxfentity.py", line 175, in load
    entity.load_tags(tags, dxfversion=dxfversion)
  File "ezdxf/src/ezdxf/entities/dxfentity.py", line 198, in load_tags
    self.dxf = self.load_dxf_attribs(processor)
  File "ezdxf/src/ezdxf/entities/spline.py", line 115, in load_dxf_attribs
    processor.load_and_recover_dxfattribs(dxf, acdb_spline)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 462, in load_and_recover_dxfattribs
    tags = self.load_dxfattribs_into_namespace(dxf, subclass, index)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 385, in load_dxfattribs_into_namespace
    return self.load_tags_into_namespace(dxf, tags[1:], subclass_definition)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 432, in load_tags_into_namespace
    dxf.set(attrib.name, value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 197, in set
    self.__setattr__(key, value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 141, in __setattr__
    self.__dict__[key] = check(value)
  File "ezdxf/src/ezdxf/entities/dxfns.py", line 130, in check
    raise const.DXFValueError(
ezdxf.lldxf.const.DXFValueError: Invalid value (0.0, 0.0, 0.0) for attribute "start_tangent" in entity SPLINE(#None).
```

**Comment by mozman** [comment]
The original DXF from this example file has no problems, I am not sure how to fix this:

1. Tangent of (0, 0, 0) is an invalid value, this value is optional, there is no need to create such bs.
2. There is no way to fix this value; which tangent should replace a (0, 0, 0) tangent?
3. A solution would be to remove this optional attribute at all, but this feature is not available for fixing routines yet
4. TrueView has another problem with a 3DSOLD object and do no load the DXF file, but we don't have to be that mean.

I will try to add the remove feature of point 3.

**Comment by mbway** [comment]
if it helps, this problem occurs for another file I found [here](https://ceco.net/autocad-blocks/architecture/top-plan-view/autocad-drawing-villa-savoye-le-corbusier-second-floor-rooftop-dwg-dxf-272)
again after converting with libredwg
[Ceco.NET-Architecture-Tm-272.dxf.zip](https://github.com/mozman/ezdxf/files/5417023/Ceco.NET-Architecture-Tm-272.dxf.zip)

**Comment by mbway** [comment]
by the way it looks like AutoCAD refuses to load these files so ultimately it's the fault of libreDWG, but if you are able to recover from it then that's great. I might post a bug report to libreDWG about it.

**Comment by mozman** [comment]
I have as solution, but for every additional exception the loading time gets a little bit longer.
