### ISSUE TITLE
Crashing loading dxf file (TypeError: Name has to be a string)

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#253]
when loading the `Architectural Example (Imperial)` example from [here](https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)
converted with ODAFileConverter
[architectural_example-imperial.dxf.zip](https://github.com/mozman/ezdxf/files/5415648/architectural_example-imperial.dxf.zip)

loading with ezdxf fails:
```
$ python examples/addons/drawing/draw_cad.py /w/odafc_output/architectural_example-imperial.dxf --out out.png
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity LWPOLYLINE(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
skipped entity ARC(#None). Reason: "invisible"
Traceback (most recent call last):
  File "examples/addons/drawing/draw_cad.py", line 86, in <module>
    _main()
  File "examples/addons/drawing/draw_cad.py", line 76, in _main
    Frontend(ctx, out).draw_layout(layout, finalize=True)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 101, in draw_layout
    self.draw_entities(reorder.ascending(layout, handle_mapping))
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 121, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 157, in draw_entity
    self.draw_composite_entity(entity, properties)
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 422, in draw_composite_entity
    self.draw_entities(set_opaque(entity.virtual_entities()))
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 109, in draw_entities
    for entity in entities:
  File "ezdxf/src/ezdxf/addons/drawing/frontend.py", line 395, in set_opaque
    for child in entities:
  File "ezdxf/src/ezdxf/entities/dimension.py", line 623, in virtual_entities
    block = self.get_geometry_block()
  File "ezdxf/src/ezdxf/entities/dimension.py", line 528, in get_geometry_block
    return self.doc.blocks.get(block_name)
  File "ezdxf/src/ezdxf/sections/blocks.py", line 215, in get
    return self.__getitem__(name)
  File "ezdxf/src/ezdxf/sections/blocks.py", line 196, in __getitem__
    block_record = cast('BlockRecord', self.block_records.get(name))
  File "ezdxf/src/ezdxf/sections/table.py", line 123, in get
    key = self.key(name)
  File "ezdxf/src/ezdxf/sections/table.py", line 80, in key
    return table_key(name)
  File "ezdxf/src/ezdxf/sections/table.py", line 39, in table_key
    raise TypeError('Name has to be a string.')
TypeError: Name has to be a string.
```

**Comment by mozman** [comment]
This is a new feature in R2018, a DIMENSION entity without an associated BLOCK, missing group tag (2, "blockname"):
![image](https://user-images.githubusercontent.com/4230966/96740891-8ec7b280-13c1-11eb-88f7-cd0357fb554e.png)

Fun fact: group code 2 is a non optional (a.k.a. required) DXF attribute according to the DXF reference.

**Comment by gribouille139** [comment]
Hello, I have similar issue : 
```
    doc = ezdxf.readfile(DXF_FILE)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/filemanagement.py", line 154, in readfile
    doc = read(fp)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/filemanagement.py", line 94, in read
    return Drawing.read(stream)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/document.py", line 282, in read
    return cls.load(tag_loader)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/document.py", line 296, in load
    doc._load(tag_loader)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/document.py", line 312, in _load
    self._load_section_dict(sections)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/document.py", line 346, in _load_section_dict
    self.tables = TablesSection(self, sections.get('TABLES', None))
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/tables.py", line 55, in __init__
    self._load(entities)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/tables.py", line 75, in _load
    self._load_table(table_name, table_records)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/tables.py", line 95, in _load_table
    new_table = table_class(self.doc, table_entities)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/table.py", line 50, in __init__
    self.load(iter(entities))
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/table.py", line 59, in load
    self._append(table_entry)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/table.py", line 186, in _append
    self.entries[self.key(entry.dxf.name)] = entry
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/table.py", line 80, in key
    return table_key(name)
  File "/usr/local/lib/python3.7/dist-packages/ezdxf/sections/table.py", line 39, in table_key
    raise TypeError('Name has to be a string.')
TypeError: Name has to be a string.
```

but  24a9d66 don't solve it.

Any idea please ? Thanks

**Comment by mbway** [comment]
Are you able to share the DXF file you are trying to load? That would make the problem much easier to diagnose
