### ISSUE TITLE
Conjugated axis required, invalid source data.

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#255]
This error occurs occasionally when converting using ODAFileConverter from dwg to dxf then loading the dxf with ezdxf.

https://dwgmodels.com/803-villa-chalet.html
[villa_chalet.dxf.zip](https://github.com/mozman/ezdxf/files/5421807/villa_chalet.dxf.zip)
I have a few other example files with the same problem if they would be useful.
```
Traceback (most recent call last):
    qsave(doc.modelspace(), os.path.join(dir_path, os.path.splitext(f)[0] + '.png'))
  File "ezdxf/addons/drawing/matplotlib.py", line 234, in qsave
    Frontend(ctx, out).draw_layout(layout, finalize=True)
  File "ezdxf/addons/drawing/frontend.py", line 93, in draw_layout
    self.draw_entities(reorder.ascending(layout, handle_mapping))
  File "ezdxf/addons/drawing/frontend.py", line 113, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 149, in draw_entity
    self.draw_composite_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 363, in draw_composite_entity
    draw_insert(entity)
  File "ezdxf/addons/drawing/frontend.py", line 351, in draw_insert
    self.draw_entities(insert.virtual_entities(
  File "ezdxf/addons/drawing/frontend.py", line 101, in draw_entities
    for entity in entities:
  File "ezdxf/explode.py", line 198, in virtual_block_reference_entities
    yield from transform(disassemble(block_layout))
  File "ezdxf/explode.py", line 165, in transform
    entity.transform(m)
  File "ezdxf/entities/ellipse.py", line 200, in transform
    e.transform(m)
  File "ezdxf/math/ellipse.py", line 130, in transform
    new_major_axis, new_minor_axis, new_ratio = rytz_axis_construction(new_major_axis, new_minor_axis)
  File "ezdxf/math/ellipse.py", line 422, in rytz_axis_construction
    raise ArithmeticError('Conjugated axis required, invalid source data.')
ArithmeticError: Conjugated axis required, invalid source data.
```
```
>>> A
Vector(0.0, 4.547473508864641e-13, 0.0)
>>> B
Vector(10335.84272920031, -4281.246236990142, 0.0)
```
I'm not sure what the fix would be for this? Perhaps these ellipses could be skipped rather than crashing ezdxf entirely? Strangely the ellipse looks reasonable so I'm not sure why the crash occurs. The ratio is 0.5 and the ellipse has significant width so it's not a really small or really thin ellipse.

**Comment by mozman** [comment]
I will look at this, it is maybe just a float precision problem.
