### ISSUE TITLE
more libreDWG errors

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#256]
I have a collection of CAD files which exhibit the exact same errors over and over when loading with ezdxf. These may not be fixable from ezdxf but incase they are genuine issues with ezdxf I thought I would share my findings. If these are not easily fixable or shouldn't be fixed then feel free to close this issue. If you can explain what is being generated and why it violates the dxf specification I could open a bug report in libreDWG instead.

color wheel from [here](https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)
converted with libredwg
[colorwh.dxf.zip](https://github.com/mozman/ezdxf/files/5421857/colorwh.dxf.zip)
```
Traceback (most recent call last):
  File "ezdxf/lldxf/tagger.py", line 87, in ascii_tags_loader
    code = int(code)
ValueError: invalid literal for int() with base 10: ' Index\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    doc = ezdxf.readfile(path)
  File "ezdxf/filemanagement.py", line 138, in readfile
    info = dxf_file_info(filename)
  File "ezdxf/filemanagement.py", line 161, in dxf_file_info
    return dxf_stream_info(fp)
  File "ezdxf/filemanagement.py", line 171, in dxf_stream_info
    info = dxf_info(stream)
  File "ezdxf/lldxf/validator.py", line 59, in dxf_info
    tag = next(tagger)
  File "ezdxf/lldxf/tagger.py", line 89, in ascii_tags_loader
    raise DXFStructureError(
ezdxf.lldxf.const.DXFStructureError: Invalid group code " Index
" at line 31.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ezdxf/recover.py", line 369, in bytes_loader
    code = int(code)
ValueError: invalid literal for int() with base 10: b' Index\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    doc = load_dxf_document(os.path.join(dir_path, f), DXFLogger(default_logger))
    doc, auditor = ezdxf.recover.readfile(path)
  File "ezdxf/recover.py", line 54, in readfile
    doc, auditor = read(fp, errors=errors)
  File "ezdxf/recover.py", line 80, in read
    recover_tool = Recover.run(stream, errors=errors)
  File "ezdxf/recover.py", line 117, in run
    sections = recover_tool.rebuild_sections(tags)
  File "ezdxf/recover.py", line 201, in rebuild_sections
    for tag in tags:
  File "ezdxf/recover.py", line 507, in byte_tag_compiler
    x = next(tags)
  File "ezdxf/lldxf/repair.py", line 74, in filter_invalid_yz_point_codes
    for tag in tagger:
  File "ezdxf/lldxf/repair.py", line 33, in tag_reorder_layer
    for tag in tagger:
  File "ezdxf/recover.py", line 372, in bytes_loader
    raise const.DXFStructureError(
ezdxf.lldxf.const.DXFStructureError: Invalid group code " Index
" at line 31.
```

the next error is extremely common and occurs for about half of the files I converted. It seems like a critical error but perhaps the y value can be omitted?
I have two examples for this error.
line weights and truetype from [here](https://knowledge.autodesk.com/support/autocad/downloads/caas/downloads/content/autocad-sample-files.html)
converted with libreDWG to dxf
[missing_y.zip](https://github.com/mozman/ezdxf/files/5421881/missing_y.zip)

```
Traceback (most recent call last):
    doc = ezdxf.readfile(path)
  File "ezdxf/filemanagement.py", line 144, in readfile
    doc = read(fp)
  File "ezdxf/filemanagement.py", line 84, in read
    return Drawing.read(stream)
  File "ezdxf/document.py", line 252, in read
    return cls.load(tag_loader)
  File "ezdxf/document.py", line 266, in load
    doc._load(tag_loader)
  File "ezdxf/document.py", line 279, in _load
    sections = loader.load_dxf_structure(tagger)
  File "ezdxf/lldxf/loader.py", line 88, in load_dxf_structure
    for entity in group_tags(tagger):
  File "ezdxf/lldxf/tags.py", line 294, in group_tags
    for tag in tags:  # has to work with iterators/generators
  File "ezdxf/lldxf/tagger.py", line 256, in tag_compiler
    raise DXFStructureError(
ezdxf.lldxf.const.DXFStructureError: Missing required y coordinate near line: 3412.
```

**Comment by mozman** [comment]
Hi!

Short answer: a total mess

colowh.dxf:  `<<<` are my remarks
```
  9
$KEYWORDS
  1
olor wheel examples using True Color and ACI (AutoCAD Color  <<< invalid line break at line 31!
 Index  <<<
  9
$INSBASE
```

linetypes.dxf has additional group code 10 (x-axis) tags without corresponding group code 11 tags (y-axis)

```
  0
TEXT
  5
AD
330
1F
100
AcDbEntity
  8
Text
  6
Continuous
370
    -3
284
     0
  7
Simplex 0 height
100
AcDbText
 10    <<< text insert point x-axis
0.38428571428571
 20  <<< y-axis 
9.33551695349895
 30  <<< z-axis
0.0
 40
0.12
  1
0.00
 10  <<< repeated insert x-axis without following y-axis
9.33551695349895
 50
0.0
 41
0.0
 51
0.0
  7
Simplex 0 height
 72
     2
 10
9.33551695349895
 31
0.0
100
AcDbText
```

And TrueView complaints about an invalid lineweight -116:
```Python
VALID_DXF_LINEWEIGHTS = (
    0, 5, 9, 13, 15, 18, 20, 25, 30, 35, 40, 50, 53, 60, 70, 80, 90,
    100, 106, 120, 140, 158, 200, 211,
)
```

**Comment by mbway** [comment]
pretty much what I expected. Sounds like there is nothing ezdxf could or should do about this. I've opened a bug report against LibreDWG instead.

Thanks for looking into what was wrong with these files.

**Comment by mozman** [comment]
Extended the recover module to load this files, this is the error log for `linetypes.dxf`:
```
INFO:ezdxf:Filter invalid point codes.
INFO:ezdxf:Reordering coordinate tags for LINE entity.
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.33551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.33551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.08551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.08551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.83551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.83551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.58551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.58551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.33551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.33551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.08551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.08551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.83551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.83551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.58551695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.58551695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.27301695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.27301695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.96051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.96051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.60801695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.60801695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.29051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.29051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'5.79051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'5.79051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'5.29051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'5.29051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.79051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.79051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.29051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.29051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.5')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.5')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.5')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.5')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.5')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.5')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.54051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.54051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'10.17329452005058')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'10.17329452005058')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.74729523286947')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.74729523286947')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.75347785733621')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.75347785733621')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.54051695349895')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.54051695349895')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.5')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.5')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.49165356017554')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.49165356017554')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'0.0')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.72648970338256')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'9.72648970338256')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.15038363820577')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'8.15038363820577')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.65040205867345')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.65040205867345')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.02542506278179')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'7.02542506278179')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.2754526791658')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'6.2754526791658')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.77550791193381')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'4.77550791193381')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.75992029360987')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.75992029360987')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.29890586984118')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'2.29890586984118')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.15832289242791')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'1.15832289242791')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.875')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.875')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.875')
DEBUG:ezdxf:remove invalid x-axis tag: (10, b'3.875')
DEBUG:ezdxf:remove misplaced axis tag: (31, b'0.0')
INFO:ezdxf:Duplicate XDATA appid ACAD in one entity
INFO:ezdxf:Duplicate XDATA appid ACAD in one entity
DEBUG:ezdxf:Fixed invalid attribute "lineweight" in entity LINE(#None) to "-1".
DEBUG:ezdxf:Fixed invalid attribute "lineweight" in entity LINE(#None) to "-1".
DEBUG:ezdxf:Fixed invalid attribute "lineweight" in entity LINE(#None) to "-1".
DEBUG:ezdxf:Fixed invalid attribute "lineweight" in entity LINE(#None) to "-1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Arial bold 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Arial 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Arial 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Arial 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:ignored DXFTag(7, 'Simplex 0 height') in subclass AcDbEntity
DEBUG:ezdxf:Fixed invalid attribute "width" in entity TEXT(#None) to "1".
INFO:ezdxf:ignored DXFTag(73, 2) in subclass AcDbText
INFO:ezdxf:creating ACAD_MLEADERSTYLE dictionary
INFO:ezdxf:creating ACAD_SCALELIST dictionary
```

**Comment by rurban** [comment]
Yep, it's a mess on my side only. Working on it.
