### ISSUE TITLE
r12writer creates invalid file on exception

### ISSUE THREAD

**Issue by kwohlfahrt** [mozman/ezdxf#28]
The r12writer context doesn't close the file properly when an exception happens. See below for examples of what happens and what I expected.

The following snippet creates an invalid dxf file:

```
>>> ezdxf.version
(0, 8, 5)
>>> from ezdxf.r12writer import r12writer
>>> with r12writer("test.dxf") as dxf:
...   raise ValueError("")
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError
```

This can be seen here:

```
>>> import ezdxf
>>> ezdxf.readfile("test.dxf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kjw53/Documents/code/survey_fix/venv/lib/python3.6/site-packages/ezdxf/filemanagement.py", line 118, in readfile
    dwg = read(fp, legacy_mode=legacy_mode, dxfversion=info.version)
  File "/home/kjw53/Documents/code/survey_fix/venv/lib/python3.6/site-packages/ezdxf/filemanagement.py", line 61, in read
    return Drawing.read(stream, legacy_mode=legacy_mode, dxfversion=dxfversion)
  File "/home/kjw53/Documents/code/survey_fix/venv/lib/python3.6/site-packages/ezdxf/drawing.py", line 296, in read
    return Drawing(tagreader)
  File "/home/kjw53/Documents/code/survey_fix/venv/lib/python3.6/site-packages/ezdxf/drawing.py", line 44, in __init__
    sections = load_dxf_structure(tagger)  # load complete DXF entity structure
  File "/home/kjw53/Documents/code/survey_fix/venv/lib/python3.6/site-packages/ezdxf/lldxf/loader.py", line 87, in load_dxf_structure
    raise DXFStructureError("DXFStructureError: missing ENDSEC tag.")
ezdxf.lldxf.const.DXFStructureError: DXFStructureError: missing ENDSEC tag.
```

However, this works (and it is also how I expected the context manager to work):

```
>>> with open("test.dxf", "w") as f:
...   dxf = R12FastStreamWriter(f)
...   try:
...     raise ValueError("")
...   finally:
...     dxf.close()
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError
```

**Comment by mozman** [comment]
Thank you, fixed the invalid implementation of context manager for r12writer
