### ISSUE TITLE
"TypeError: an integer is required" when trying to get paper limits by psp.get_paper_limits()

### ISSUE THREAD

**Issue by mkondratyev85** [mozman/ezdxf#360]
My version of python is 3.8, my version of ezdxf is 0.15.2.

When I try to get the paper limits I get the error. Here is the code of minimum working example:

```python
import ezdxf
doc = ezdxf.new()
psp = doc.layout('Layout1')
psp.get_paper_limits()
```

And here is the error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/ezdxf/layouts/layout.py", line 648, in get_paper_limits
    return self.dxf.limmin[0:2], self.dxf.limmax[0:2]
  File "src/ezdxf/acc/vector.pyx", line 512, in ezdxf.acc.vector.Vec3.__getitem__
TypeError: an integer is required
```

It worked well on the older versions of ezdxf.

**Comment by mkondratyev85** [comment]
Thank you for the answer.
