### ISSUE TITLE
BytesWarning in lldxf.repair.py

### ISSUE THREAD

**Issue by johnthagen** [mozman/ezdxf#371]
For our projects we run our tests with the [`-bb` flag](https://docs.python.org/3/using/cmdline.html#cmdoption-b) to catch `str` and `bytes` mismatches. Our tests fail when `ezdxf` is imported.

Consider `main.py`:

```py
import ezdxf
```

And invoke it:

```bash
(venv) $ pip list
Package    Version
---------- -------
ezdxf      0.15.2
pip        21.0.1
pyparsing  2.4.7
setuptools 53.0.0

(venv) $ python --version
Python 3.9.1

(venv) $ python -bb simple.py 
Traceback (most recent call last):
  File "dxf-test/simple.py", line 1, in <module>
    import ezdxf
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/__init__.py", line 21, in <module>
    from ezdxf.filemanagement import readzip, new, read, readfile, decode_base64
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/filemanagement.py", line 6, in <module>
    from ezdxf.tools.standards import setup_drawing
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/tools/standards.py", line 4, in <module>
    from ezdxf.render.arrows import ARROWS
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/render/__init__.py", line 8, in <module>
    from .path import Path, Command, has_path_support, make_path, from_matplotlib_path
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/render/path.py", line 20, in <module>
    from ezdxf.entities import LWPolyline, Polyline, Hatch, Line, Spline
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/entities/__init__.py", line 10, in <module>
    from .xdata import XData, EmbeddedObjects
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/entities/xdata.py", line 13, in <module>
    from ezdxf.lldxf.repair import filter_invalid_xdata_group_codes
  File "dxf-test/venv/lib/python3.9/site-packages/ezdxf/lldxf/repair.py", line 172, in <module>
    COORDINATE_FIXING_TOOLBOX = {
BytesWarning: Comparison between bytes and string
```

**Comment by johnthagen** [comment]
The offending line seems to be:

https://github.com/mozman/ezdxf/blob/f9c0d10febbfb29d26a316164267d3059079f79f/src/ezdxf/lldxf/repair.py#L174

With this commented out, the `import` succeeds.

**Comment by mozman** [comment]
This is valid, required and on purpose!
