### ISSUE TITLE
There was a problem deleting all

### ISSUE THREAD

**Issue by liunx7594** [mozman/ezdxf#423]
```
import ezdxf

wcad = ezdxf.readfile(r'a.dxf')
wmsp = wcad.modelspace()
for m in list(wmsp):
    wmsp.delete_entity(m)
wcad.save()

```

The error is as follows

Traceback (most recent call last):
  File "C:/Users/L/Documents/code/pythonProject/test_log.py", line 7, in <module>
    wcad.save()
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\document.py", line 474, in save
    self.write(fp, fmt=fmt)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\document.py", line 527, in write
    self.export_sections(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\document.py", line 548, in export_sections
    self.objects.export_dxf(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\sections\objects.py", line 57, in export_dxf
    self._entity_space.export_dxf(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\entitydb.py", line 344, in export_dxf
    entity.export_dxf(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\entities\dxfentity.py", line 551, in export_dxf
    self.export_entity(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\entities\dxfgroups.py", line 90, in export_entity
    self.export_group(tagwriter)
  File "C:\Users\L\.conda\envs\py3.7\lib\site-packages\ezdxf-0.16.2b1-py3.7.egg\ezdxf\entities\dxfgroups.py", line 97, in export_group
    handle = entity.dxf.handle
AttributeError: 'Insert' object has no attribute 'dxf'

**Comment by liunx7594** [comment]
The document is as follows

[a.zip](https://github.com/mozman/ezdxf/files/6402875/a.zip)

**Comment by mozman** [comment]
This bug will be fixed, but be aware **deleting** is much more complicated than you think:

1. Call the auditor to fix **known** issues **before** exporting the DXF file: `doc.audit()`
2. There is no guarantee that AutoCAD will open this file,  even if ezdxf does not raise an error.

**Comment by mozman** [comment]
A safer way would be to create an empty template DXF by the CAD application and just add new entities to this template.
