### ISSUE TITLE
Multileader drawing crash

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#474]
When drawing this file: 
[multileaders.dxf.zip](https://github.com/mozman/ezdxf/files/6677557/multileaders.dxf.zip)

ezdxf crashes with:
```
$ python draw_cad.py /tmp/multileaders.dxf
skipped entity TEXT(#None). Reason: "invisible"
Traceback (most recent call last):
  File "draw_cad.py", line 88, in <module>
    _main()
  File "draw_cad.py", line 78, in _main
    Frontend(ctx, out).draw_layout(layout, finalize=True)
  File "ezdxf/addons/drawing/frontend.py", line 149, in draw_layout
    self.draw_entities(
  File "ezdxf/addons/drawing/frontend.py", line 174, in draw_entities
    self.draw_entity(entity, properties)
  File "ezdxf/addons/drawing/frontend.py", line 197, in draw_entity
    self.draw_proxy_graphic(entity)
  File "ezdxf/addons/drawing/frontend.py", line 508, in draw_proxy_graphic
    self.draw_entities(gfx.virtual_entities())
  File "ezdxf/addons/drawing/frontend.py", line 165, in draw_entities
    for entity in entities:
  File "ezdxf/proxygraphic.py", line 158, in virtual_entities
    result = method(self._buffer[index + 8: index + size])
  File "ezdxf/proxygraphic.py", line 484, in unicode_text2
    attribs['style'] = self._get_style(font_filename, big_font_filename)
  File "ezdxf/proxygraphic.py", line 513, in _get_style
    self._doc.styles.new(font, dxfattribs={'font': font,
  File "ezdxf/sections/table.py", line 112, in new
    raise const.DXFTableEntryError(
ezdxf.lldxf.const.DXFTableEntryError: STYLE  already exists!

```

**Comment by mbway** [comment]
this issue hasn't been fixed in all cases. This example is from the same source file as the original
[example.dxf.zip](https://github.com/mozman/ezdxf/files/6694177/example.dxf.zip)

the exception is exactly the same
