### ISSUE TITLE
Difficulty running the main module

### ISSUE THREAD

**Issue by mbway** [mozman/ezdxf#478]
When I run `$ python src/ezdxf --help` from the repo root (or running the main module from my IDE) I get the error:
```
Traceback (most recent call last):
  File "/lib/python3.9/subprocess.py", line 73, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "ezdxf/src/ezdxf/__main__.py", line 5, in <module>
    from ezdxf import options, print_config
  File "ezdxf/src/ezdxf/__init__.py", line 22, in <module>
    from ezdxf.colors import (
  File "ezdxf/src/ezdxf/colors.py", line 4, in <module>
    from ezdxf.tools.rgb import *  # ezdxf.colors will replace ezdxf.tools.rgb
  File "ezdxf/src/ezdxf/tools/__init__.py", line 5, in <module>
    from uuid import uuid4
  File "/lib/python3.9/uuid.py", line 59, in <module>
    import platform
  File "/lib/python3.9/platform.py", line 119, in <module>
    import subprocess
  File "/lib/python3.9/subprocess.py", line 80, in <module>
    import selectors
  File "/lib/python3.9/selectors.py", line 11, in <module>
    import math
  File "ezdxf/src/ezdxf/math/__init__.py", line 8, in <module>
    from ._ctypes import *
  File "ezdxf/src/ezdxf/math/_ctypes.py", line 30, in <module>
    from ._vector import (
  File "ezdxf/src/ezdxf/math/_vector.py", line 6, in <module>
    import random
  File "/lib/python3.9/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from partially initialized module 'math' (most likely due to a circular import) (ezdxf/src/ezdxf/math/__init__.py)
```

It isn't ideal that one of the packages in ezdxf shares the name of the system 'math' module. The installed ezdxf main module works correctly, but while developing it would be nice to be able to run the main module from the source code.

**Comment by mozman** [comment]
I never got such an error, maybe because I have installed the package by pip in development mode: `pip install -e .`. From here on the `ezdxf --help` command uses always the development version from the src folder. 

Just tested on Windows: `py src/ezdxf --help` also works without any errors, same for `python src/ezdxf --help` (Windows supports forward slashes :).

**Comment by mbway** [comment]
I did some more tests and it looks like it's related to conda, because i can run the main module outside of conda but not inside (even in an entirely clean/empty conda environment)

**Comment by mozman** [comment]
Is there anything I can do or can we close this issue?

**Comment by mbway** [comment]
You can close it. It doesn't seem like anyone else is having issues. I can work around it with `pip install -e` which is better anyway (thanks for that tip)
