### ISSUE TITLE
Crash Log from a reporting program.

### ISSUE THREAD

**Issue by tatarize** [mozman/ezdxf#493]
The code here just calls rather standard readfile.

```
MeerK40t crash log. Version: 0.7.0 RC-6 on win32
Traceback (most recent call last):
  File "meerk40t\gui\wxmeerk40t.py", line 2797, in on_click_open
  File "meerk40t\gui\wxmeerk40t.py", line 2504, in load
  File "meerk40t\core\elements.py", line 4524, in load
  File "meerk40t\dxf\dxf_io.py", line 52, in load
  File "ezdxf\filemanagement.py", line 154, in readfile
  File "ezdxf\filemanagement.py", line 94, in read
  File "ezdxf\document.py", line 282, in read
  File "ezdxf\document.py", line 296, in load
  File "ezdxf\document.py", line 312, in _load
  File "ezdxf\document.py", line 339, in _load_section_dict
  File "ezdxf\lldxf\loader.py", line 140, in load_and_bind_dxf_content
  File "ezdxf\lldxf\loader.py", line 132, in load_dxf_entities
  File "ezdxf\entities\factory.py", line 57, in load
  File "ezdxf\entities\dxfentity.py", line 196, in load
  File "ezdxf\entities\dxfentity.py", line 219, in load_tags
  File "ezdxf\entities\lwpolyline.py", line 96, in load_dxf_attribs
  File "ezdxf\entities\lwpolyline.py", line 102, in load_vertices
  File "ezdxf\entities\lwpolyline.py", line 395, in from_tags
TypeError: 'NoneType' object is not iterable
```

Appears to be the line: `for tag in tags` https://github.com/mozman/ezdxf/blob/55ba99a5c3193a70d0f95732fdc8e0b55ae3c6c2/src/ezdxf/entities/lwpolyline.py#L395

I'm sorry I don't know what data initially crashed this since it's a log from not-me. So if this isn't enough info, please close the issue. 

This log has an ezdxf origin'ed crash. Using ezdxf 0.16.3.

**Comment by mozman** [comment]
Can you upload the (zipped) DXF file? Which Application created the DXF file?

This seems to be a DXF structure error - LWPOLYLINE without an `AcDbPolyline` subclass section.

**Comment by mozman** [comment]
TrueView 2021 (AutoCAD) does not load DXF files with LWPOLYLINE entities without a `AcDbPolyline` section.

     The following error was encountered while reading
     in LWPOLYLINE starting at line 1976:
     Class separator for class AcDbPolyline expected
     Invalid or incomplete DXF input -- drawing discarded.

**Comment by tatarize** [comment]
I do not have the original dxf file myself, it was a log that got uploaded for a crash within my program which uses ezdxf. I'm not sure what the person did to crash it there. If this isn't enough info to correct the error, go ahead and close the issue. I just get uploaded crash logs. So I can't recreate it.
