### ISSUE TITLE
reading writing entites

### ISSUE THREAD

**Issue by Mambix** [mozman/ezdxf#5]
what is the best way to read multiple DXF files and combine them into one?

I tried to read the entities from dxf but saving them into an empty dxf with `add_entity(e)` always produces and error.

I also did not find and easy way to move entities. Lets say I want to move them with a certain vector before saving them to DXF.

```
Traceback (most recent call last):
    dxf.saveas(target)
  File "C:\Python27\lib\site-packages\ezdxf\drawing.py", line 285, in saveas
    self.save(encoding=encoding)
  File "C:\Python27\lib\site-packages\ezdxf\drawing.py", line 296, in save
    self.write(fp)
  File "C:\Python27\lib\site-packages\ezdxf\drawing.py", line 303, in write
    self.sections.write(stream)
  File "C:\Python27\lib\site-packages\ezdxf\sections\sections.py", line 91, in write
    section.write(stream)
  File "C:\Python27\lib\site-packages\ezdxf\sections\entities.py", line 38, in write
    self._entity_space.write(stream, layout_keys)
  File "C:\Python27\lib\site-packages\ezdxf\entityspace.py", line 141, in write
    layout_spaces[key].write(stream)
  File "C:\Python27\lib\site-packages\ezdxf\entityspace.py", line 37, in write
    tags = self._entitydb[handle]
  File "C:\Python27\lib\site-packages\ezdxf\database.py", line 40, in __getitem__
    return self._database[handle]
KeyError: u'BA'
```

**Comment by mozman** [comment]
You have to use the add_<entity>() methods to add new DXF entities like add_line() or add_lwpolyline()
see docs: http://ezdxf.readthedocs.io/en/latest/layouts.html#create-new-entities
