### ISSUE TITLE
Boundingbox calculation error related to text

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#636]
[S148.zip](https://github.com/mozman/ezdxf/files/8132048/S148.zip)
```
from ezdxf import recover
from ezdxf import bbox

dxf_doc, dxf_auditor = recover.readfile('s148.dxf')
msp = dxf_doc.modelspace()
cache = bbox.Cache()
# get overall bounding box
first_bbox = bbox.extents(msp, cache=cache)
# bounding box of all LINE entities
second_bbox = bbox.extend(msp.query("LINE"), cache=cache)
```
```
findfont: Font family ['gbenor'] not found. Falling back to DejaVu Sans.
Traceback (most recent call last):
  File "E:\WortkingTestProjects\ezdxf_bug\test.py", line 8, in <module>
    first_bbox = bbox.extents(msp, cache=cache)
  File "D:\Python\Python310\lib\site-packages\ezdxf\bbox.py", line 141, in extents
    for box in multi_flat(entities, flatten=flatten, cache=cache):
  File "D:\Python\Python310\lib\site-packages\ezdxf\tools\text.py", line 61, in __init__
    self._text_width: float = font.text_width(text)
  File "D:\Python\Python310\lib\site-packages\ezdxf\tools\fonts.py", line 497, in text_width
    path = self._support_lib.get_text_path(text, self._font_properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\tools\_matplotlib_font_support.py", line 94, in get_text_path
    return TextPath(
  File "D:\Python\Python310\lib\site-packages\matplotlib\textpath.py", line 388, in __init__
    super().__init__(
  File "D:\Python\Python310\lib\site-packages\matplotlib\path.py", line 130, in __init__
    _api.check_shape((None, 2), vertices=vertices)
  File "D:\Python\Python310\lib\site-packages\matplotlib\_api\__init__.py", line 164, in check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
```

I think the reason is unkonw text fomt family

**Comment by mozman** [comment]
The  `Matplotlib` runtime error is handled in the latest  beta version.
