### ISSUE TITLE
Incorrect of virtual entities for Insert with ellipse

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#702]
**Describe the bug**
wrong explode of insert

**To Reproduce**
This code will fail in ezdxf-18.6b
```
import sys
import matplotlib.pyplot as plt
import ezdxf
from ezdxf import recover
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend

# Safe loading procedure (requires ezdxf v0.17.2)
try:
    doc, auditor = recover.readfile('1111.dxf')
except IOError:
    print(f'Not a DXF file or a generic I/O error.')
    sys.exit(1)
except ezdxf.DXFStructureError:
    print(f'Invalid or corrupted DXF file.')
    sys.exit(2)

# The auditor.errors attribute stores severe errors,
# which may raise exceptions when rendering.
if not auditor.has_errors:
    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    Frontend(ctx, out).draw_layout(doc.modelspace(), finalize=True)
    fig.savefig('1111.png', dpi=300)
```

**Confidential Data**
[1111.zip](https://github.com/mozman/ezdxf/files/9062964/1111.zip)
code result
![1111](https://user-images.githubusercontent.com/5702248/177759414-362e1fa2-f4c0-4fd8-8b5b-cfdee58d9e38.png)
autocad result
![1657192065506](https://user-images.githubusercontent.com/5702248/177759619-c07e1de4-ed00-4c1e-af1f-343bbb166e9f.png)

**Expected behavior**
![1657192118886](https://user-images.githubusercontent.com/5702248/177759866-8947a56c-287f-4af2-b93c-0a78cd72fcf6.png)

**Screenshots**
![1657192150149](https://user-images.githubusercontent.com/5702248/177759876-d82c8bf1-cf0c-43d2-b8e9-910902c0fd39.png)

**Comment by mozman** [comment]
Should be fixed:

![Screenshot 2022-07-07 161040](https://user-images.githubusercontent.com/4230966/177794615-0c40c6ef-08f3-469d-83ca-838a89892c1a.png)

**Comment by chibai** [comment]
> Should be fixed:
> 
> ![Screenshot 2022-07-07 161040](https://user-images.githubusercontent.com/4230966/177794615-0c40c6ef-08f3-469d-83ca-838a89892c1a.png)

Thank  you for your hotfix~ But the code actually failed in ezdxf0.18b6 with matplotlib 3.5.1 in python 3.10.
```
File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 179, in draw_layout
    self.draw_entities(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 215, in draw_entities
    self.draw_entity(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 236, in draw_entity
    draw_method(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 440, in draw_hatch_entity
    self.out.draw_filled_paths(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\matplotlib.py", line 166, in draw_filled_paths
    Path(vertices, codes),
  File "D:\Python\Python310\lib\site-packages\matplotlib\path.py", line 130, in __init__
    _api.check_shape((None, 2), vertices=vertices)
  File "D:\Python\Python310\lib\site-packages\matplotlib\_api\__init__.py", line 164, in check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
```

**Comment by mozman** [comment]
Do you use the latest version  of `ezdxf` from github?

**Comment by chibai** [comment]
> Do you use the latest version of `ezdxf` from github?

Nope. Now I see. I will close this issue after ezdxf 0.18b7

**Comment by mozman** [comment]
I really hope the next release is the final v0.18.

**Comment by chibai** [comment]
> I really hope the next release is the final v0.18.

Why, I thought v1.00 is the real start of the project~~

**Comment by mozman** [comment]
final == non-beta == default version on PyPI

**Comment by chibai** [comment]
> final == non-beta == default version on PyPI

OK, I misunderstand you as giving up this project.
Why not be the official version of v0.18， I didn't really know the difference between beta and official version.

**Comment by chibai** [comment]
I tried this code in 0.18bv7 with python 3.10 and matplotlib 3.5.2
It failed
```
Traceback (most recent call last):
  File "E:\WortkingTestProjects\ezdxf_bug\draw.py", line 25, in <module>
    Frontend(ctx, out).draw_layout(doc.modelspace(), finalize=True)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 183, in draw_layout
    self.draw_entities(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 216, in draw_entities
    self.draw_entity(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 237, in draw_entity
    draw_method(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 441, in draw_hatch_entity
    self.out.draw_filled_paths(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\matplotlib.py", line 166, in draw_filled_paths
    Path(vertices, codes),
  File "D:\Python\Python310\lib\site-packages\matplotlib\path.py", line 130, in __init__
    _api.check_shape((None, 2), vertices=vertices)
  File "D:\Python\Python310\lib\site-packages\matplotlib\_api\__init__.py", line 164, in check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
```
