### ISSUE TITLE
Missing hatch compare to the Autocad

### ISSUE THREAD

**Issue by chibai** [mozman/ezdxf#706]
**Describe the bug**
I'm not complain about hatch pattern but the hatch location itself.

**To Reproduce**
```
import sys
import matplotlib.pyplot as plt
import ezdxf
from ezdxf import recover
from ezdxf.addons.drawing import RenderContext, Frontend
from ezdxf.addons.drawing.matplotlib import MatplotlibBackend

# Safe loading procedure (requires ezdxf v0.14):
try:
    doc, auditor = recover.readfile('7888_1.dxf')
except IOError:
    print(f'Not a DXF file or a generic I/O error.')
    sys.exit(1)
except ezdxf.DXFStructureError:
    print(f'Invalid or corrupted DXF file.')
    sys.exit(2)

# The auditor.errors attribute stores severe errors,
# which may raise exceptions when rendering.
if not auditor.has_errors:
    fig = plt.figure()
    ax = fig.add_axes([0, 0, 1, 1])
    ctx = RenderContext(doc)
    out = MatplotlibBackend(ax)
    Frontend(ctx, out).draw_layout(doc.modelspace(), finalize=True)
    fig.savefig('7888_1.png', dpi=300)
```

**Confidential Data**
[7888_1.zip](https://github.com/mozman/ezdxf/files/9100511/7888_1.zip)

**Expected behavior**
AutoCad
![1657701985914](https://user-images.githubusercontent.com/5702248/178691488-e75287e8-0f02-47da-acbc-f5fcd0df0352.png)

**Screenshots**
ezdxf drawing
![7888_1](https://user-images.githubusercontent.com/5702248/178691549-e3449359-048a-4d91-ad59-340dc5fd8339.png)

**Comment by chibai** [comment]
I tried this code in 0.18bv7 with python 3.10
It failed
```
Traceback (most recent call last):
  File "E:\WortkingTestProjects\ezdxf_bug\draw.py", line 25, in <module>
    Frontend(ctx, out).draw_layout(doc.modelspace(), finalize=True)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 188, in draw_layout
    self.draw_entities(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 216, in draw_entities
    self.draw_entity(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 237, in draw_entity
    draw_method(entity, properties)
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\frontend.py", line 441, in draw_hatch_entity
    self.out.draw_filled_paths(
  File "D:\Python\Python310\lib\site-packages\ezdxf\addons\drawing\matplotlib.py", line 166, in draw_filled_paths
    Path(vertices, codes),
  File "D:\Python\Python310\lib\site-packages\matplotlib\path.py", line 130, in __init__
    _api.check_shape((None, 2), vertices=vertices)
  File "D:\Python\Python310\lib\site-packages\matplotlib\_api\__init__.py", line 164, in check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
```

**Comment by chibai** [comment]
I have a stupid suggestion, try_catch the whole  'self.draw_entity(entity, properties)', so each drawing of element is independent

**Comment by mozman** [comment]
The exception is fixed.

This HATCH has an edge boundary with gaps, which means one ore more edges are not connected by common vertices. The current implementation ignores such open boundary paths, because rendering these open path caused unwanted artefacts in another sample file.

I don't  wanna change this behavior because all this special cases are not documented and the handling of the HATCH entity gets more and more complex. Any change which fixes one special-case problem can introduce a problem for another special case. I am tired of handling that mess, sorry!
