### ISSUE TITLE
'TypeError: must be char, not unicode' when using ezdxf

### ISSUE THREAD

**Issue by spierepf** [mozman/ezdxf#79]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/peter/.local/lib/python2.7/site-packages/dxf2svg/__main__.py", line 23, in <module>
    from dxf2svg.pycore import *
  File "/home/peter/.local/lib/python2.7/site-packages/dxf2svg/pycore.py", line 27, in <module>
    import ezdxf
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/__init__.py", line 16, in <module>
    from ezdxf.filemanagement import new, read, readfile, readzip
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/filemanagement.py", line 7, in <module>
    from ezdxf.drawing import Drawing
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/drawing.py", line 12, in <module>
    from ezdxf.dxffactory import dxffactory
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/dxffactory.py", line 8, in <module>
    from ezdxf.legacy import LegacyDXFFactory
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/legacy/__init__.py", line 6, in <module>
    from .factory import LegacyDXFFactory
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/legacy/factory.py", line 9, in <module>
    from . import tableentries
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/legacy/tableentries.py", line 254, in <module>
    class VPort(DXFEntity):
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/legacy/tableentries.py", line 256, in VPort
    TEMPLATE = ExtendedTags.from_text(_VPORTTEMPLATE)
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/extendedtags.py", line 315, in from_text
    return cls(internal_tag_compiler(text))
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/extendedtags.py", line 36, in __init__
    self._setup(iterable)
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/extendedtags.py", line 182, in _setup
    tag = collect_subclass(None)  # preceding tags without a subclass
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/extendedtags.py", line 95, in collect_subclass
    tag = next(tagstream)
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/tagger.py", line 53, in internal_tag_compiler
    yield DXFVertex(code, point)  # 2d/3d point
  File "/home/peter/.local/lib/python2.7/site-packages/ezdxf/lldxf/types.py", line 82, in __init__
    super(DXFVertex, self).__init__(code, array('d', value))
TypeError: must be char, not unicode

```

**Comment by mozman** [comment]
which ezdxf version?

**Comment by spierepf** [comment]
According to pip, I am using 0.8.10.

**Comment by mozman** [comment]
This version of ezdxf should work on linux with python 2.7, I run tests with tox on manjaro in a virtualbox environment without any error messages. This error occurs on on the very basic `import ezdxf` level, so I don't know what the problem is here, sorry.

That is the reason why I dropped the python 2 support in v0.9 and later, try to use Python 3.
