### ISSUE TITLE
ezdxf.lldxf.const.DXFStructureError: DXFStructureError: missing EOF tag.

### ISSUE THREAD

**Issue by Balasass** [mozman/ezdxf#85]
try to load the drawing with simple code you give at tutorial:

`import ezdxf

dwg = ezdxf.readfile("Tre-Gate-8meter.dxf")`

and this is happen:
`Traceback (most recent call last):
  File "D:/PyCharm/DGW3/test.py", line 3, in <module>
    dwg = ezdxf.readfile("Tre-Gate-8meter.dxf")
  File "D:\PyCharm\DGW3\venv\lib\site-packages\ezdxf\filemanagement.py", line 141, in readfile
    dwg = read(fp, legacy_mode=legacy_mode, dxfversion=info.version)
  File "D:\PyCharm\DGW3\venv\lib\site-packages\ezdxf\filemanagement.py", line 79, in read
    return Drawing.read(stream, legacy_mode=legacy_mode, dxfversion=dxfversion)
  File "D:\PyCharm\DGW3\venv\lib\site-packages\ezdxf\drawing.py", line 412, in read
    return Drawing(tagreader)
  File "D:\PyCharm\DGW3\venv\lib\site-packages\ezdxf\drawing.py", line 61, in __init__
    sections = load_dxf_structure(tagger)  # load complete DXF entity structure
  File "D:\PyCharm\DGW3\venv\lib\site-packages\ezdxf\lldxf\loader.py", line 135, in load_dxf_structure
    raise DXFStructureError('DXFStructureError: missing EOF tag.')
ezdxf.lldxf.const.DXFStructureError: DXFStructureError: missing EOF tag.
`

**Comment by mozman** [comment]
Is "Tre-Gate-8meter.dxf" created by ezdxf?

**Comment by Balasass** [comment]
no, my team using Autocad ver.2013

**Comment by mozman** [comment]
This file is maybe corrupt.

**Comment by Balasass** [comment]
tried using different file and it works now, and the difference between the working file and the one is not is the size of the file, the working one is below 1000 KB and the one is not working is above 3000 KB

is there a limit that library can process?

**Comment by mozman** [comment]
No, only hardware, OS and interpreter limitations, I tested ezdxf successful with 30-50 MB files on a 16GB workstation and a 64-bit CPython interpreter.
