### ISSUE TITLE
Importing package occurs UnicodeDecodeError

### ISSUE THREAD

**Issue by lavender-lee** [mozman/ezdxf#953]
I used the following script to install `ezdxf` package
```
>conda create --name=python-dxf-env python=3.9

Collecting package metadata (current_repodata.json): done
Solving environment: done


> activate python-dxf-env

> (python-dxf-env) E:\>pip install ezdxf

> python
```

then I import package:

```python
>>> import ezdxf
```

```
>>> import ezdxf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\__init__.py", line 36, in <module>
    from ezdxf.filemanagement import readzip, new, read, readfile, decode_base64
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\filemanagement.py", line 12, in <module>
    from ezdxf.document import Drawing
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\document.py", line 32, in <module>
    from ezdxf.layouts import Modelspace, Paperspace
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\layouts\__init__.py", line 3, in <module>
    from .base import BaseLayout, VirtualLayout
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\layouts\base.py", line 18, in <module>
    from ezdxf.graphicsfactory import CreatorInterface
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\graphicsfactory.py", line 30, in <module>
    from ezdxf.render.dim_linear import multi_point_linear_dimension
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\render\__init__.py", line 20, in <module>
    from .mleader import (
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\render\mleader.py", line 39, in <module>
    from ezdxf.tools import text_size, text as text_tools
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\tools\text_size.py", line 9, in <module>
    from ezdxf.fonts import fonts
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\fonts.py", line 733, in <module>
    _load_font_manager()
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\fonts.py", line 286, in _load_font_manager
    build_font_manager_cache(fm_path)
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\fonts.py", line 326, in build_font_manager_cache
    font_manager.build()
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\font_manager.py", line 409, in build
    self.scan_all(dirs + list(options.support_dirs))
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\font_manager.py", line 417, in scan_all
    self.scan_folder(Path(folder).expanduser())
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\font_manager.py", line 431, in scan_folder
    font_face = get_ttf_font_face(file)
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\site-packages\ezdxf\fonts\font_manager.py", line 461, in get_ttf_font_face
    family = record.string.decode(record.getEncoding())
  File "D:\Win10\Anaconda3\envs\python-dxf-env\lib\encodings\utf_16_be.py", line 16, in decode
    return codecs.utf_16_be_decode(input, errors, True)
UnicodeDecodeError: 'utf-16-be' codec can't decode byte 0x6f in position 8: truncated data
```

**Comment by lavender-lee** [comment]
I debug this issue by PyCharm, I add `try-except` to avoid this issue

![image](https://github.com/mozman/ezdxf/assets/35004095/b19a18d4-2de8-4175-9efa-9002322b7922)
